
services:
  db:
    image: postgres:15
    networks: 
      - smarthome-nw
    environment:
      POSTGRES_DB: devicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data


  smarthome:
    build:
      context: .
      dockerfile: smarthome/Dockerfile
    image: smarthome-image
    networks: 
      - smarthome-nw
    ports:
      - '3000:3000'
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: secret
      PGDATABASE: devicesdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # <-- Hier wird der Docker-Socket gemountet. Damit er Zugriff auf den Docker-Daemon des Hosts bekommt.
    depends_on:
      db:
        condition: service_healthy

  # falls der Thermostat-Container noch nicht von Anfang an vorhanden sein soll, muss das Image manuell gebaut und dieser Teil auskommentiert werden:          docker build -t thermostat-image -f thermostat/Dockerfile
  thermostat:
    container_name: web-service-thermostat-1
    build:
      context: .
      dockerfile: thermostat/Dockerfile
    image: thermostat-image
    networks: 
      - smarthome-nw
    ports:
      - "6001:6001"
    environment:
      PORT: 6001
      DEFAULT_TEMPERATURE: 22
      ROOM_ID: "Wohnzimmer"
  
  fensterkontakt:
    container_name: web-service-fensterkontakt-2
    build:
      context: .
      dockerfile: fensterkontakt/Dockerfile
    image: fensterkontakt-image
    networks: 
      - smarthome-nw
    ports:
      - "3021:3021"
    environment:
      PORT: 3021
  
  
volumes:
  pgdata:

networks:
  smarthome-nw:
    driver: bridge 
